### ISSUE TITLE
[Suggest idea] add self update

### ISSUE THREAD

**Issue by congaterori** [TartSoft/WDOS3#2]
add self update
when the file open it will download the version.txt on GitHub and unzip use unzip.exe
`unzip.exe version.zip > nul`
then rename the new version.txt to new-ver.txt and the old one still version.txt
use fc command to compare and compare new-ver.txt with version.txt
https://ss64.com/nt/fc.html
if 2 files are the same then it will go to noupdate (no update) if they are the same go to startupdate (start update) else is go to error
```
fc new-ver.txt version.txt
if %ERRORLEVEL% == 2 goto error
if %ERRORLEVEL% == 1 goto startupdate
if %ERRORLEVEL% == 0 goto noupdate
```
in startupdate you need to download the project WDOS3 from Github then unzip it using unzip.exe
to download the project WDOS3 you need powershell command but fortunately powershell commands can run in batch file
for windows 7
`powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/TartSoft/WDOS3.zip', 'WDOS3-main.zip')"`
for windows 10
`powershell -Command "Invoke-WebRequest https://github.com/TartSoft/WDOS3.zip -OutFile WDOS3-main.zip"`

then use unzip
`unzip.exe WDOS3-main.zip`

**Comment by duongletrieu** [comment]
Thanks congaterori!

**Comment by duongletrieu** [comment]
Actually i just a pure 10 years old

**Comment by duongletrieu** [comment]
*poor

**Comment by congaterori** [comment]
I'm 15 year old
Tôi 15 tuổi
Cứ gọi bạn hoặc gọi bằng anh em gì cũng được

Vào 15:04 Th 2, 10 thg 1 2022 Le Trieu Duong ***@***.***> đã
viết:

**Comment by duongletrieu** [comment]
anh?

**Comment by duongletrieu** [comment]
cảm ơn bn nhé
